version: '3.8'

services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Spring Profile untuk Docker
      SPRING_PROFILES_ACTIVE: docker
      
      # Database configuration
      DB_URL: ${DB_URL:-jdbc:postgresql://localhost:5432/todo_list}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # JWT configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      
      # Application configuration
      SERVER_PORT: ${SERVER_PORT:-8080}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      SECURITY_LOG_LEVEL: ${SECURITY_LOG_LEVEL:-WARN}
      
      # JPA Configuration
      JPA_DDL_AUTO: ${JPA_DDL_AUTO:-validate}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL:-false}
      JPA_FORMAT_SQL: ${JPA_FORMAT_SQL:-false}
      
      # Flyway
      FLYWAY_ENABLED: ${FLYWAY_ENABLED:-true}
    # ports:
    #   - "${APP_PORT:-8080}:8080"
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  todo-network:
    driver: bridge